### ISSUE TITLE
Exception in AsyncResetEvent crashes application

### ISSUE THREAD

**Issue by sloto** [burakoner/ApiSharp#3]
Hi, thanks for your work! 
I'm using [OKX Api library](https://github.com/burakoner/OKX.Api) and I'm encountering this exception several seconds after I dispose web socket client:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at ApiSharp.Models.AsyncResetEvent.<>c__DisplayClass5_0.<WaitAsync>b__0() in E:\Github\ApiSharp\ApiSharp\Models\AsyncResetEvent.cs:line 47
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

```
Can you please provide some solution or work around for this issue. It's pretty important for me as it crashes my application.

You can reproduce it with this code:

```

using OKX.Api;

var options = new OKXWebSocketApiClientOptions
{
    AutoReconnect = true,
    ReconnectInterval = TimeSpan.FromSeconds(10),
    DemoTradingService = true,
    BaseAddress = OKXApiAddresses.Demo.WebSocketPublicAddress,
};

var wsClient = new OKXWebSocketApiClient(options);
await wsClient.OrderBookTrading.MarketData.SubscribeToOrderBookAsync(Console.WriteLine, "BTC-USDT", OKX.Api.Enums.OkxOrderBookType.OrderBook_5);
await Task.Delay(TimeSpan.FromSeconds(10));
wsClient.Dispose();

await Task.Delay(TimeSpan.FromSeconds(300));
```

**Comment by burakoner** [comment]
Thank you very much for your solution suggestion
